//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLicenseManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_AppLicenseManager_Entities : DbContext
    {
        public db_AppLicenseManager_Entities()
            : base("name=db_AppLicenseManager_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_chaveativacao> tb_chaveativacao { get; set; }
        public virtual DbSet<tb_fabricantes> tb_fabricantes { get; set; }
        public virtual DbSet<tb_maquinas> tb_maquinas { get; set; }
        public virtual DbSet<tb_permissoes> tb_permissoes { get; set; }
        public virtual DbSet<tb_setores> tb_setores { get; set; }
        public virtual DbSet<tb_sitemap> tb_sitemap { get; set; }
        public virtual DbSet<tb_softwares> tb_softwares { get; set; }
        public virtual DbSet<tb_status> tb_status { get; set; }
        public virtual DbSet<tb_tipolicenca> tb_tipolicenca { get; set; }
        public virtual DbSet<tb_tipoUsuario> tb_tipoUsuario { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
        public virtual DbSet<vw_permissaoacesso> vw_permissaoacesso { get; set; }
    }
}
