//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_chaveativacao
    {
        public int cdChaveAtivacao { get; set; }
        public int cdSoftware { get; set; }
        public int cdMaquina { get; set; }
        public int cdStatus { get; set; }
        public int cdTipoLicenca { get; set; }
        public Nullable<System.DateTime> data_aquisicao { get; set; }
        public Nullable<System.DateTime> data_validade { get; set; }
        public string chaveAtivacao { get; set; }
        public int deleted { get; set; }
    }
}
