//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_maquinas
    {
        public int cdMaquina { get; set; }
        public string hostname { get; set; }
        public int cdSetor { get; set; }
        public int cdStatus { get; set; }
        public int deleted { get; set; }
    }
}
