//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sitemap
    {
        public int cdMenu { get; set; }
        public Nullable<int> cdMenuPai { get; set; }
        public string descMenu { get; set; }
        public string URL { get; set; }
        public string icone_fa { get; set; }
        public string icone_bootstrap { get; set; }
    }
}
