//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipoUsuario
    {
        public int cdTipoUsuario { get; set; }
        public string tipoUsuario { get; set; }
        public int deleted { get; set; }
    }
}
