//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        public int cdUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public int cdTipoUsuario { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public int cdStatusUsuario { get; set; }
        public int deleted { get; set; }
    }
}
